add_newline = false

# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$docker_context\
$package\
$buf\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""


[git_branch]
format = " [$symbol$branch]($style) "

[git_status]
style = "bold #FFA500"
ahead = "⇡${count}"
diverged = "⇕[⇡${ahead_count}](bold green)[⇣${behind_count}](bold red)"
behind = "⇣${count}"

[git_metrics]
added_style = "green" 	
deleted_style =	"red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false


[docker_context]
disabled = true

[ruby]
format = " [$symbol($version )]($style)"
symbol = " "

[nodejs]
format = " [$symbol($version )]($style)"
