[package]
name = "bin_chicken"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
dialoguer = "0.10.2"
dirs = "4.0.0"
trash = "2.1.5"
